spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: javastart.pl.homework@gmail.com
    password: JavaStart.pl1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    pl:
      javastart: DEBUG